package ec.edu.ucuenca.cesedefunciones;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class dth_cdf_informe_analista implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DTH_CDF_INFORME_ANALISTA_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "DTH_CDF_INFORME_ANALISTA_ID_SEQ", name = "DTH_CDF_INFORME_ANALISTA_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("inconvenientesPresentados")
   private java.lang.Boolean inconvenientesPresentados;

   @org.kie.api.definition.type.Label("informeLegalRequerido")
   private java.lang.Boolean informeLegalRequerido;

   @org.kie.api.definition.type.Label("motivoInformeLegal")
   private java.lang.String motivoInformeLegal;

   private org.jbpm.document.Document historial;

   @org.kie.api.definition.type.Label(value = "comentarios")
   private java.lang.String comentarios;

   public dth_cdf_informe_analista()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Boolean getInconvenientesPresentados()
   {
      return this.inconvenientesPresentados;
   }

   public void setInconvenientesPresentados(
         java.lang.Boolean inconvenientesPresentados)
   {
      this.inconvenientesPresentados = inconvenientesPresentados;
   }

   public java.lang.Boolean getInformeLegalRequerido()
   {
      return this.informeLegalRequerido;
   }

   public void setInformeLegalRequerido(java.lang.Boolean informeLegalRequerido)
   {
      this.informeLegalRequerido = informeLegalRequerido;
   }

   public java.lang.String getMotivoInformeLegal()
   {
      return this.motivoInformeLegal;
   }

   public void setMotivoInformeLegal(java.lang.String motivoInformeLegal)
   {
      this.motivoInformeLegal = motivoInformeLegal;
   }

   public org.jbpm.document.Document getHistorial()
   {
      return this.historial;
   }

   public void setHistorial(org.jbpm.document.Document historial)
   {
      this.historial = historial;
   }

   public java.lang.String getComentarios()
   {
      return this.comentarios;
   }

   public void setComentarios(java.lang.String comentarios)
   {
      this.comentarios = comentarios;
   }

   public dth_cdf_informe_analista(java.lang.Long id,
         java.lang.Boolean inconvenientesPresentados,
         java.lang.Boolean informeLegalRequerido,
         java.lang.String motivoInformeLegal,
         org.jbpm.document.Document historial, 
         java.lang.String comentarios)
   {
      this.id = id;
      this.inconvenientesPresentados = inconvenientesPresentados;
      this.informeLegalRequerido = informeLegalRequerido;
      this.motivoInformeLegal = motivoInformeLegal;
      this.historial = historial;
      this.comentarios = comentarios;
   }

}