package ec.edu.ucuenca.cesedefunciones;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class dth_cdf_informe_legal implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DTH_CDF_INFORME_LEGAL_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "DTH_CDF_INFORME_LEGAL_ID_SEQ", name = "DTH_CDF_INFORME_LEGAL_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "informeLegal")
   private java.lang.String informeLegal;
   
   private org.jbpm.document.Document archivoInformeLegal;

   public dth_cdf_informe_legal()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getInformeLegal()
   {
      return this.informeLegal;
   }

   public void setInformeLegal(java.lang.String informeLegal)
   {
      this.informeLegal = informeLegal;
   }
   
   public org.jbpm.document.Document getArchivoInformeLegal()
   {
      return this.archivoInformeLegal;
   }

   public void setArchivoInformeLegal(org.jbpm.document.Document archivoInformeLegal)
   {
      this.archivoInformeLegal = archivoInformeLegal;
   }

   public dth_cdf_informe_legal(java.lang.Long id,
         java.lang.String informeLegal,
         org.jbpm.document.Document archivoInformeLegal)
   {
      this.id = id;
      this.informeLegal = informeLegal;
      this.archivoInformeLegal = archivoInformeLegal;
   }

}