package ec.edu.ucuenca.cesedefunciones;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class dth_cdf_solicitud implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "DTH_CDF_SOLICITUD_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "DTH_CDF_SOLICITUD_ID_SEQ", name = "DTH_CDF_SOLICITUD_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("usuario")
   private java.lang.String usuario;

   @org.kie.api.definition.type.Label("dependencia")
   private java.lang.String dependencia;

   @org.kie.api.definition.type.Label("fechaRegistro")
   private java.util.Date fechaRegistro;

   @org.kie.api.definition.type.Label("fechaSolicitud")
   private java.util.Date fechaSolicitud;

   @org.kie.api.definition.type.Label("motivoRenuncia")
   private java.lang.String motivoRenuncia;

   private org.jbpm.document.Document oficioSolicitud;

   @org.kie.api.definition.type.Label("informeAprobado")
   private java.lang.Boolean informeAprobado;

   private org.jbpm.document.Document informeDth;

   @org.kie.api.definition.type.Label("aceptada")
   private java.lang.Boolean aceptada;

   @org.kie.api.definition.type.Label("comentariosAceptacion")
   private java.lang.String comentariosAceptacion;

   @org.kie.api.definition.type.Label("ultimoDiaFunciones")
   private java.util.Date ultimoDiaFunciones;

   @org.kie.api.definition.type.Label("fechaAceptacion")
   private java.util.Date fechaAceptacion;

   @org.kie.api.definition.type.Label("numDocumentoAceptacion")
   private java.lang.String numDocumentoAceptacion;

   private org.jbpm.document.Document oficioRespuesta;

   @org.kie.api.definition.type.Label("entregado")
   private java.lang.Boolean entregado;

   @org.kie.api.definition.type.Label("fechaEntrega")
   private java.util.Date fechaEntrega;

   @org.kie.api.definition.type.Label("cancelado")
   private java.lang.Boolean cancelado;

   @org.kie.api.definition.type.Label("fechaCancelacion")
   private java.util.Date fechaCancelacion;

   @org.kie.api.definition.type.Label("dependenciaId")
   private java.lang.String dependenciaId;

   public dth_cdf_solicitud()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getUsuario()
   {
      return this.usuario;
   }

   public void setUsuario(java.lang.String usuario)
   {
      this.usuario = usuario;
   }

   public java.lang.String getDependencia()
   {
      return this.dependencia;
   }

   public void setDependencia(java.lang.String dependencia)
   {
      this.dependencia = dependencia;
   }

   public java.util.Date getFechaRegistro()
   {
      return this.fechaRegistro;
   }

   public void setFechaRegistro(java.util.Date fechaRegistro)
   {
      this.fechaRegistro = fechaRegistro;
   }

   public java.util.Date getFechaSolicitud()
   {
      return this.fechaSolicitud;
   }

   public void setFechaSolicitud(java.util.Date fechaSolicitud)
   {
      this.fechaSolicitud = fechaSolicitud;
   }

   public java.lang.String getMotivoRenuncia()
   {
      return this.motivoRenuncia;
   }

   public void setMotivoRenuncia(java.lang.String motivoRenuncia)
   {
      this.motivoRenuncia = motivoRenuncia;
   }

   public org.jbpm.document.Document getOficioSolicitud()
   {
      return this.oficioSolicitud;
   }

   public void setOficioSolicitud(org.jbpm.document.Document oficioSolicitud)
   {
      this.oficioSolicitud = oficioSolicitud;
   }

   public java.lang.Boolean getInformeAprobado()
   {
      return this.informeAprobado;
   }

   public void setInformeAprobado(java.lang.Boolean informeAprobado)
   {
      this.informeAprobado = informeAprobado;
   }

   public org.jbpm.document.Document getInformeDth()
   {
      return this.informeDth;
   }

   public void setInformeDth(org.jbpm.document.Document informeDth)
   {
      this.informeDth = informeDth;
   }

   public java.lang.Boolean getAceptada()
   {
      return this.aceptada;
   }

   public void setAceptada(java.lang.Boolean aceptada)
   {
      this.aceptada = aceptada;
   }

   public java.lang.String getComentariosAceptacion()
   {
      return this.comentariosAceptacion;
   }

   public void setComentariosAceptacion(java.lang.String comentariosAceptacion)
   {
      this.comentariosAceptacion = comentariosAceptacion;
   }

   public java.util.Date getUltimoDiaFunciones()
   {
      return this.ultimoDiaFunciones;
   }

   public void setUltimoDiaFunciones(java.util.Date ultimoDiaFunciones)
   {
      this.ultimoDiaFunciones = ultimoDiaFunciones;
   }

   public java.util.Date getFechaAceptacion()
   {
      return this.fechaAceptacion;
   }

   public void setFechaAceptacion(java.util.Date fechaAceptacion)
   {
      this.fechaAceptacion = fechaAceptacion;
   }

   public java.lang.String getNumDocumentoAceptacion()
   {
      return this.numDocumentoAceptacion;
   }

   public void setNumDocumentoAceptacion(java.lang.String numDocumentoAceptacion)
   {
      this.numDocumentoAceptacion = numDocumentoAceptacion;
   }

   public org.jbpm.document.Document getOficioRespuesta()
   {
      return this.oficioRespuesta;
   }

   public void setOficioRespuesta(org.jbpm.document.Document oficioRespuesta)
   {
      this.oficioRespuesta = oficioRespuesta;
   }

   public java.lang.Boolean getEntregado()
   {
      return this.entregado;
   }

   public void setEntregado(java.lang.Boolean entregado)
   {
      this.entregado = entregado;
   }

   public java.util.Date getFechaEntrega()
   {
      return this.fechaEntrega;
   }

   public void setFechaEntrega(java.util.Date fechaEntrega)
   {
      this.fechaEntrega = fechaEntrega;
   }

   public java.lang.Boolean getCancelado()
   {
      return this.cancelado;
   }

   public void setCancelado(java.lang.Boolean cancelado)
   {
      this.cancelado = cancelado;
   }

   public java.util.Date getFechaCancelacion()
   {
      return this.fechaCancelacion;
   }

   public void setFechaCancelacion(java.util.Date fechaCancelacion)
   {
      this.fechaCancelacion = fechaCancelacion;
   }

   public java.lang.String getDependenciaId()
   {
      return this.dependenciaId;
   }

   public void setDependenciaId(java.lang.String dependenciaId)
   {
      this.dependenciaId = dependenciaId;
   }

   public dth_cdf_solicitud(java.lang.Long id, java.lang.String usuario,
         java.lang.String dependencia, java.util.Date fechaRegistro,
         java.util.Date fechaSolicitud, java.lang.String motivoRenuncia,
         org.jbpm.document.Document oficioSolicitud,
         java.lang.Boolean informeAprobado,
         org.jbpm.document.Document informeDth, java.lang.Boolean aceptada,
         java.lang.String comentariosAceptacion,
         java.util.Date ultimoDiaFunciones, java.util.Date fechaAceptacion,
         java.lang.String numDocumentoAceptacion,
         org.jbpm.document.Document oficioRespuesta,
         java.lang.Boolean entregado, java.util.Date fechaEntrega,
         java.lang.Boolean cancelado, java.util.Date fechaCancelacion,
         java.lang.String dependenciaId)
   {
      this.id = id;
      this.usuario = usuario;
      this.dependencia = dependencia;
      this.fechaRegistro = fechaRegistro;
      this.fechaSolicitud = fechaSolicitud;
      this.motivoRenuncia = motivoRenuncia;
      this.oficioSolicitud = oficioSolicitud;
      this.informeAprobado = informeAprobado;
      this.informeDth = informeDth;
      this.aceptada = aceptada;
      this.comentariosAceptacion = comentariosAceptacion;
      this.ultimoDiaFunciones = ultimoDiaFunciones;
      this.fechaAceptacion = fechaAceptacion;
      this.numDocumentoAceptacion = numDocumentoAceptacion;
      this.oficioRespuesta = oficioRespuesta;
      this.entregado = entregado;
      this.fechaEntrega = fechaEntrega;
      this.cancelado = cancelado;
      this.fechaCancelacion = fechaCancelacion;
      this.dependenciaId = dependenciaId;
   }

}