package ec.edu.ucuenca.cesedefunciones;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class dth_cdf_solicitante implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "DTH_CDF_SOLICITANTE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "DTH_CDF_SOLICITANTE_ID_SEQ", name = "DTH_CDF_SOLICITANTE_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("cedula")
   private java.lang.String cedula;

   @org.kie.api.definition.type.Label("nombre")
   private java.lang.String nombre;

   @org.kie.api.definition.type.Label("cargo")
   private java.lang.String cargo;

   @org.kie.api.definition.type.Label("dependencia")
   private java.lang.String dependencia;

   @org.kie.api.definition.type.Label("modalidadContrato")
   private java.lang.String modalidadContrato;

   @org.kie.api.definition.type.Label("emailParticular")
   private java.lang.String emailParticular;

   @org.kie.api.definition.type.Label("telefonoContacto")
   private java.lang.String telefonoContacto;

   @org.kie.api.definition.type.Label("extensionTelefonica")
   private java.lang.Integer extensionTelefonica;

   @org.kie.api.definition.type.Label(value = "modalidadContratoId")
   private java.lang.String modalidadContratoId;

   @org.kie.api.definition.type.Label(value = "dependenciaId")
   private java.lang.String dependenciaId;

   @org.kie.api.definition.type.Label(value = "cargoId")
   private java.lang.String cargoId;

   public dth_cdf_solicitante()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCedula()
   {
      return this.cedula;
   }

   public void setCedula(java.lang.String cedula)
   {
      this.cedula = cedula;
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.String getCargo()
   {
      return this.cargo;
   }

   public void setCargo(java.lang.String cargo)
   {
      this.cargo = cargo;
   }

   public java.lang.String getDependencia()
   {
      return this.dependencia;
   }

   public void setDependencia(java.lang.String dependencia)
   {
      this.dependencia = dependencia;
   }

   public java.lang.String getModalidadContrato()
   {
      return this.modalidadContrato;
   }

   public void setModalidadContrato(java.lang.String modalidadContrato)
   {
      this.modalidadContrato = modalidadContrato;
   }

   public java.lang.String getEmailParticular()
   {
      return this.emailParticular;
   }

   public void setEmailParticular(java.lang.String emailParticular)
   {
      this.emailParticular = emailParticular;
   }

   public java.lang.String getTelefonoContacto()
   {
      return this.telefonoContacto;
   }

   public void setTelefonoContacto(java.lang.String telefonoContacto)
   {
      this.telefonoContacto = telefonoContacto;
   }

   public java.lang.Integer getExtensionTelefonica()
   {
      return this.extensionTelefonica;
   }

   public void setExtensionTelefonica(java.lang.Integer extensionTelefonica)
   {
      this.extensionTelefonica = extensionTelefonica;
   }

   public java.lang.String getModalidadContratoId()
   {
      return this.modalidadContratoId;
   }

   public void setModalidadContratoId(java.lang.String modalidadContratoId)
   {
      this.modalidadContratoId = modalidadContratoId;
   }

   public java.lang.String getDependenciaId()
   {
      return this.dependenciaId;
   }

   public void setDependenciaId(java.lang.String dependenciaId)
   {
      this.dependenciaId = dependenciaId;
   }

   public java.lang.String getCargoId()
   {
      return this.cargoId;
   }

   public void setCargoId(java.lang.String cargoId)
   {
      this.cargoId = cargoId;
   }

   public dth_cdf_solicitante(java.lang.Long id, java.lang.String cedula,
         java.lang.String nombre, java.lang.String cargo,
         java.lang.String dependencia, java.lang.String modalidadContrato,
         java.lang.String emailParticular, java.lang.String telefonoContacto,
         java.lang.Integer extensionTelefonica,
         java.lang.String modalidadContratoId, java.lang.String dependenciaId,
         java.lang.String cargoId)
   {
      this.id = id;
      this.cedula = cedula;
      this.nombre = nombre;
      this.cargo = cargo;
      this.dependencia = dependencia;
      this.modalidadContrato = modalidadContrato;
      this.emailParticular = emailParticular;
      this.telefonoContacto = telefonoContacto;
      this.extensionTelefonica = extensionTelefonica;
      this.modalidadContratoId = modalidadContratoId;
      this.dependenciaId = dependenciaId;
      this.cargoId = cargoId;
   }

}